baseURL = "https://thesilentscream.xyz/"
languageCode = "en-us"
title = "My Blog"
theme = "PaperMod"
paginate = 5

googleAnalytics = "UA-190578527-1"



[params]
env = "production"
description = "This is a hugo website based on PaperMod theme "
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = false
comments = true
Search = true
enableRobotsTXT = true


[params.homeInfoParams]
  Title = "നിശബ്ദമായ നിലവിളികൾ"
  Content = """
mairu! janichu poyille thoughts on everyday life
"""

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 10


[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/sherukkaduva"

[[params.socialIcons]]
  name = "email"
  url = "mailto:thesilentscreamer91@gmail.com"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/thesilentscreamer"



  